# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qwTVcym9Cbqa2FELUNzXC5o0Kda2mL8F
"""



from modul import Transaction as transaction

while True:
    print("\n------------ Supermarket Andi -------------")
    print("-------------- Main Menu ------------------\n")
    print("1. Tambah Item")
    print("2. Ubah Nama Item")
    print("3. ubah quantity")
    print("4. ubah harga")
    print("5. Hapus Item")
    print("6. Reset Keranjang Belanja")
    print("7. Lihat Keranjang Belanja")
    print("8. Lihat Total Harga")
    print("9. Keluar")

    choice = input("Masukkan pilihan (1-9): ")
    print("\n")

    if choice == "1":
        transaction.add_item()
    elif choice == "2":
        transaction.update_name_item()
    elif choice == "3":
        transaction.update_quantity_item()
    elif choice == "4":
        transaction.update_price_item()
    elif choice == "5":
        transaction.delete_item()
    elif choice == "6":
        transaction.reset_order()
    elif choice == "7":
        transaction.check_list_order()
    elif choice == "8":
        transaction.total_price()
    elif choice == "9":
        print("Terima kasih telah berbelanja di Supermarket Andi")
        break
    else:
        print("Pilihan tidak benar. Masukkan pilihan (1-9)")